# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b71b8f4ab205986638f2aab6408b3be7720344a80cdaea05c86a91c5abc95bdf86a395636889d760ded4d42f65aecfaaade509b23afa98a9bccc120a06f3d9

test:
  secret_key_base: 9e279654948c66be811ac6a8d3a0a34453093c03c8480c4282652e346b9b8a8352e90dfecbe6ea364810ba5edbf993aef83c112c6dba8e14e3a12812baf644e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
